### PR TITLE
Require Groonga 11.0.6 or later

### PR DESCRIPTION
**Pull request by komainu8**

### CODE REVIEW

**Comment by kou** [comment]
Which commit does that require Groonga 11.0.6 or later?

**Comment by komainu8** [comment]
I was thinking that PGroonga required Groonga 11.0.6 or later since this version when I saw the below news. 

https://github.com/pgroonga/pgroonga.github.io/commit/dca905c64f5c7405e383dae593c86c21c4e3c6fd#diff-3e2c9c58eff3c4caeb391b60ecfaa6b1e2efb2a9f87f564c3950ce14207d4c29R10

Sorry, I don't know a specific commit.

**Comment by kou** [comment]
Ah, OK. I wanted to implement "Added support for crash recovery". But it's not implemented yet. So Groonga 11.0.6 isn't required yet.

**Comment by komainu8** [comment]
I see.
This PR is close.

**Pull request closed without merging**
