### PR TITLE
ci windows: add PostgreSQL 15

### LINKED ISSUE #256: pgroonga postgres 15 windows binaries are missing
Hello
On releases page there is release for Postgres 15 for Linux but the windows binary is 404.
Thanks for the extension.

### PR DESCRIPTION
**Pull request by komainu8**
GitHub: Fix #256.
Reported by Raif Atef. Thanks!!!

### CODE REVIEW

**Comment by rwasef1830** [comment]
@komainu8 it's not yet on the releases page the binaries for windows pg 15.

**Comment by komainu8** [comment]
We'll provide PGroonga with PostgreSQL 15 for Windows in the next release.
The next release is scheduled on around the end of the month.

Do you need PGroonga with PostgreSQL 15 for Windows soon?

**Comment by rwasef1830** [comment]
Yes, but I was able to find the artifact from the pull request page, so no problem.

**Comment by CGSgeosite** [comment]
We also look forward to pgroonga dockerfile for pg15. thank you

**Comment by komainu8** [comment]
@CGSgeosite 
We are also getting PGroonga's dockerfile for PostgreSQL 15 ready now.

**Comment by kou** [comment]
> We also look forward to pgroonga dockerfile for pg15. thank you

https://github.com/pgroonga/docker/issues/13

**Pull request merged**
